# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7076450e22bd36355582bc94be0bcf580d1746db2b2483454bed89bb6083ad08b1234d9ca9d67579dd356048a0dc2d721a797b1d2d4b5c20e348ed6d1df32791

test:
  secret_key_base: a441c9a03881c911c1572679434291fad8e2755555f127cb78168589c14d19f5c0926724652dc309948cd5d4dd3faaadcd246910c681bf93a99dd57f00825356

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
